### ISSUE TITLE
Task list

### ISSUE THREAD

**Issue by axtens** [exercism/rexx#3]
- [ ] [accumulate \(deprecated)](https://github.com/exercism/problem-specifications/tree/main/exercises/accumulate)
- [ ] [acronym](https://github.com/exercism/problem-specifications/tree/main/exercises/acronym)
- [ ] [affine-cipher](https://github.com/exercism/problem-specifications/tree/main/exercises/affine-cipher)
- [ ] [all-your-base](https://github.com/exercism/problem-specifications/tree/main/exercises/all-your-base)
- [ ] [allergies](https://github.com/exercism/problem-specifications/tree/main/exercises/allergies)
- [ ] [alphametics](https://github.com/exercism/problem-specifications/tree/main/exercises/alphametics)
- [ ] [anagram](https://github.com/exercism/problem-specifications/tree/main/exercises/anagram)
- [ ] [armstrong-numbers](https://github.com/exercism/problem-specifications/tree/main/exercises/armstrong-numbers)
- [ ] [atbash-cipher](https://github.com/exercism/problem-specifications/tree/main/exercises/atbash-cipher)
- [ ] [bank-account](https://github.com/exercism/problem-specifications/tree/main/exercises/bank-account)
- [ ] [beer-song](https://github.com/exercism/problem-specifications/tree/main/exercises/beer-song)
- [ ] [binary \(deprecated)](https://github.com/exercism/problem-specifications/tree/main/exercises/binary)
- [ ] [binary-search](https://github.com/exercism/problem-specifications/tree/main/exercises/binary-search)
- [ ] [binary-search-tree](https://github.com/exercism/problem-specifications/tree/main/exercises/binary-search-tree)
- [ ] [bob](https://github.com/exercism/problem-specifications/tree/main/exercises/bob)
- [ ] [book-store](https://github.com/exercism/problem-specifications/tree/main/exercises/book-store)
- [ ] [bowling](https://github.com/exercism/problem-specifications/tree/main/exercises/bowling)
- [ ] [change](https://github.com/exercism/problem-specifications/tree/main/exercises/change)
- [ ] [circular-buffer](https://github.com/exercism/problem-specifications/tree/main/exercises/circular-buffer)
- [ ] [clock](https://github.com/exercism/problem-specifications/tree/main/exercises/clock)
- [ ] [collatz-conjecture](https://github.com/exercism/problem-specifications/tree/main/exercises/collatz-conjecture)
- [ ] [complex-numbers](https://github.com/exercism/problem-specifications/tree/main/exercises/complex-numbers)
- [ ] [connect](https://github.com/exercism/problem-specifications/tree/main/exercises/connect)
- [ ] [counter \(deprecated)](https://github.com/exercism/problem-specifications/tree/main/exercises/counter)
- [ ] [crypto-square](https://github.com/exercism/problem-specifications/tree/main/exercises/crypto-square)
- [ ] [custom-set](https://github.com/exercism/problem-specifications/tree/main/exercises/custom-set)
- [ ] [darts](https://github.com/exercism/problem-specifications/tree/main/exercises/darts)
- [ ] [diamond](https://github.com/exercism/problem-specifications/tree/main/exercises/diamond)
- [ ] [difference-of-squares](https://github.com/exercism/problem-specifications/tree/main/exercises/difference-of-squares)
- [ ] [diffie-hellman](https://github.com/exercism/problem-specifications/tree/main/exercises/diffie-hellman)
- [ ] [dnd-character](https://github.com/exercism/problem-specifications/tree/main/exercises/dnd-character)
- [ ] [dominoes](https://github.com/exercism/problem-specifications/tree/main/exercises/dominoes)
- [ ] [dot-dsl](https://github.com/exercism/problem-specifications/tree/main/exercises/dot-dsl)
- [ ] [error-handling](https://github.com/exercism/problem-specifications/tree/main/exercises/error-handling)
- [ ] [etl](https://github.com/exercism/problem-specifications/tree/main/exercises/etl)
- [ ] [flatten-array](https://github.com/exercism/problem-specifications/tree/main/exercises/flatten-array)
- [ ] [food-chain](https://github.com/exercism/problem-specifications/tree/main/exercises/food-chain)
- [ ] [forth](https://github.com/exercism/problem-specifications/tree/main/exercises/forth)
- [ ] [gigasecond](https://github.com/exercism/problem-specifications/tree/main/exercises/gigasecond)
- [ ] [go-counting](https://github.com/exercism/problem-specifications/tree/main/exercises/go-counting)
- [ ] [grade-school](https://github.com/exercism/problem-specifications/tree/main/exercises/grade-school)
- [ ] [grains](https://github.com/exercism/problem-specifications/tree/main/exercises/grains)
- [ ] [grep](https://github.com/exercism/problem-specifications/tree/main/exercises/grep)
- [ ] [hamming](https://github.com/exercism/problem-specifications/tree/main/exercises/hamming)
- [ ] [hangman](https://github.com/exercism/problem-specifications/tree/main/exercises/hangman)
- [ ] [hello-world](https://github.com/exercism/problem-specifications/tree/main/exercises/hello-world)
- [ ] [hexadecimal \(deprecated)](https://github.com/exercism/problem-specifications/tree/main/exercises/hexadecimal)
- [ ] [high-scores](https://github.com/exercism/problem-specifications/tree/main/exercises/high-scores)
- [ ] [house](https://github.com/exercism/problem-specifications/tree/main/exercises/house)
- [ ] [isbn-verifier](https://github.com/exercism/problem-specifications/tree/main/exercises/isbn-verifier)
- [ ] [isogram](https://github.com/exercism/problem-specifications/tree/main/exercises/isogram)
- [ ] [killer-sudoku-helper](https://github.com/exercism/problem-specifications/tree/main/exercises/killer-sudoku-helper)
- [ ] [kindergarten-garden](https://github.com/exercism/problem-specifications/tree/main/exercises/kindergarten-garden)
- [ ] [knapsack](https://github.com/exercism/problem-specifications/tree/main/exercises/knapsack)
- [ ] [largest-series-product](https://github.com/exercism/problem-specifications/tree/main/exercises/largest-series-product)
- [ ] [leap](https://github.com/exercism/problem-specifications/tree/main/exercises/leap)
- [ ] [ledger](https://github.com/exercism/problem-specifications/tree/main/exercises/ledger)
- [ ] [lens-person](https://github.com/exercism/problem-specifications/tree/main/exercises/lens-person)
- [ ] [linked-list](https://github.com/exercism/problem-specifications/tree/main/exercises/linked-list)
- [ ] [list-ops](https://github.com/exercism/problem-specifications/tree/main/exercises/list-ops)
- [ ] [luhn](https://github.com/exercism/problem-specifications/tree/main/exercises/luhn)
- [ ] [markdown](https://github.com/exercism/problem-specifications/tree/main/exercises/markdown)
- [ ] [matching-brackets](https://github.com/exercism/problem-specifications/tree/main/exercises/matching-brackets)
- [ ] [matrix](https://github.com/exercism/problem-specifications/tree/main/exercises/matrix)
- [ ] [meetup](https://github.com/exercism/problem-specifications/tree/main/exercises/meetup)
- [ ] [micro-blog](https://github.com/exercism/problem-specifications/tree/main/exercises/micro-blog)
- [ ] [minesweeper](https://github.com/exercism/problem-specifications/tree/main/exercises/minesweeper)
- [ ] [nth-prime](https://github.com/exercism/problem-specifications/tree/main/exercises/nth-prime)
- [ ] [nucleotide-codons \(deprecated)](https://github.com/exercism/problem-specifications/tree/main/exercises/nucleotide-codons)
- [ ] [nucleotide-count](https://github.com/exercism/problem-specifications/tree/main/exercises/nucleotide-count)
- [ ] [ocr-numbers](https://github.com/exercism/problem-specifications/tree/main/exercises/ocr-numbers)
- [ ] [octal \(deprecated)](https://github.com/exercism/problem-specifications/tree/main/exercises/octal)
- [ ] [paasio](https://github.com/exercism/problem-specifications/tree/main/exercises/paasio)
- [ ] [palindrome-products](https://github.com/exercism/problem-specifications/tree/main/exercises/palindrome-products)
- [ ] [pangram](https://github.com/exercism/problem-specifications/tree/main/exercises/pangram)
- [ ] [parallel-letter-frequency](https://github.com/exercism/problem-specifications/tree/main/exercises/parallel-letter-frequency)
- [ ] [pascals-triangle](https://github.com/exercism/problem-specifications/tree/main/exercises/pascals-triangle)
- [ ] [perfect-numbers](https://github.com/exercism/problem-specifications/tree/main/exercises/perfect-numbers)
- [ ] [phone-number](https://github.com/exercism/problem-specifications/tree/main/exercises/phone-number)
- [ ] [pig-latin](https://github.com/exercism/problem-specifications/tree/main/exercises/pig-latin)
- [ ] [point-mutations \(deprecated)](https://github.com/exercism/problem-specifications/tree/main/exercises/point-mutations)
- [ ] [poker](https://github.com/exercism/problem-specifications/tree/main/exercises/poker)
- [ ] [pov](https://github.com/exercism/problem-specifications/tree/main/exercises/pov)
- [ ] [prime-factors](https://github.com/exercism/problem-specifications/tree/main/exercises/prime-factors)
- [ ] [protein-translation](https://github.com/exercism/problem-specifications/tree/main/exercises/protein-translation)
- [ ] [proverb](https://github.com/exercism/problem-specifications/tree/main/exercises/proverb)
- [ ] [pythagorean-triplet](https://github.com/exercism/problem-specifications/tree/main/exercises/pythagorean-triplet)
- [ ] [queen-attack](https://github.com/exercism/problem-specifications/tree/main/exercises/queen-attack) 
- [ ] [rail-fence-cipher](https://github.com/exercism/problem-specifications/tree/main/exercises/rail-fence-cipher)
- [ ] [raindrops](https://github.com/exercism/problem-specifications/tree/main/exercises/raindrops)
- [ ] [rational-numbers](https://github.com/exercism/problem-specifications/tree/main/exercises/rational-numbers)
- [ ] [react](https://github.com/exercism/problem-specifications/tree/main/exercises/react)
- [ ] [rectangles](https://github.com/exercism/problem-specifications/tree/main/exercises/rectangles)
- [ ] [resistor-color](https://github.com/exercism/problem-specifications/tree/main/exercises/resistor-color)
- [ ] [resistor-color-duo](https://github.com/exercism/problem-specifications/tree/main/exercises/resistor-color-duo)
- [ ] [resistor-color-trio](https://github.com/exercism/problem-specifications/tree/main/exercises/resistor-color-trio)
- [ ] [rest-api](https://github.com/exercism/problem-specifications/tree/main/exercises/rest-api)
- [ ] [reverse-string](https://github.com/exercism/problem-specifications/tree/main/exercises/reverse-string)
- [ ] [rna-transcription](https://github.com/exercism/problem-specifications/tree/main/exercises/rna-transcription)
- [ ] [robot-name](https://github.com/exercism/problem-specifications/tree/main/exercises/robot-name)
- [ ] [robot-simulator](https://github.com/exercism/problem-specifications/tree/main/exercises/robot-simulator)
- [ ] [roman-numerals](https://github.com/exercism/problem-specifications/tree/main/exercises/roman-numerals)
- [ ] [rotational-cipher](https://github.com/exercism/problem-specifications/tree/main/exercises/rotational-cipher)
- [ ] [run-length-encoding](https://github.com/exercism/problem-specifications/tree/main/exercises/run-length-encoding)
- [ ] [saddle-points](https://github.com/exercism/problem-specifications/tree/main/exercises/saddle-points)
- [ ] [satellite](https://github.com/exercism/problem-specifications/tree/main/exercises/satellite)
- [ ] [say](https://github.com/exercism/problem-specifications/tree/main/exercises/say)
- [ ] [scale-generator](https://github.com/exercism/problem-specifications/tree/main/exercises/scale-generator)
- [ ] [scrabble-score](https://github.com/exercism/problem-specifications/tree/main/exercises/scrabble-score) 
- [ ] [secret-handshake](https://github.com/exercism/problem-specifications/tree/main/exercises/secret-handshake)
- [ ] [series](https://github.com/exercism/problem-specifications/tree/main/exercises/series)
- [ ] [sgf-parsing](https://github.com/exercism/problem-specifications/tree/main/exercises/sgf-parsing)
- [ ] [sieve](https://github.com/exercism/problem-specifications/tree/main/exercises/sieve)
- [ ] [simple-cipher](https://github.com/exercism/problem-specifications/tree/main/exercises/simple-cipher)
- [ ] [simple-linked-list](https://github.com/exercism/problem-specifications/tree/main/exercises/simple-linked-list)
- [ ] [space-age](https://github.com/exercism/problem-specifications/tree/main/exercises/space-age)
- [ ] [spiral-matrix](https://github.com/exercism/problem-specifications/tree/main/exercises/spiral-matrix)
- [ ] [square-root](https://github.com/exercism/problem-specifications/tree/main/exercises/square-root)
- [ ] [state-of-tic-tac-toe](https://github.com/exercism/problem-specifications/tree/main/exercises/state-of-tic-tac-toe)
- [ ] [strain](https://github.com/exercism/problem-specifications/tree/main/exercises/strain)
- [ ] [sublist](https://github.com/exercism/problem-specifications/tree/main/exercises/sublist)
- [ ] [sum-of-multiples](https://github.com/exercism/problem-specifications/tree/main/exercises/sum-of-multiples)
- [ ] [tournament](https://github.com/exercism/problem-specifications/tree/main/exercises/tournament)
- [ ] [transpose](https://github.com/exercism/problem-specifications/tree/main/exercises/transpose)
- [ ] [tree-building](https://github.com/exercism/problem-specifications/tree/main/exercises/tree-building)
- [ ] [triangle](https://github.com/exercism/problem-specifications/tree/main/exercises/triangle)
- [ ] [trinary \(deprecated)](https://github.com/exercism/problem-specifications/tree/main/exercises/trinary)
- [ ] [twelve-days](https://github.com/exercism/problem-specifications/tree/main/exercises/twelve-days)
- [ ] [two-bucket](https://github.com/exercism/problem-specifications/tree/main/exercises/two-bucket)
- [ ] [two-fer](https://github.com/exercism/problem-specifications/tree/main/exercises/two-fer)
- [ ] [variable-length-quantity](https://github.com/exercism/problem-specifications/tree/main/exercises/variable-length-quantity)
- [ ] [word-count](https://github.com/exercism/problem-specifications/tree/main/exercises/word-count)
- [ ] [word-search](https://github.com/exercism/problem-specifications/tree/main/exercises/word-search)
- [ ] [wordy](https://github.com/exercism/problem-specifications/tree/main/exercises/wordy)
- [ ] [yacht](https://github.com/exercism/problem-specifications/tree/main/exercises/yacht)
- [ ] [zebra-puzzle](https://github.com/exercism/problem-specifications/tree/main/exercises/zebra-puzzle)
- [ ] [zipper](https://github.com/exercism/problem-specifications/tree/main/exercises/zipper)

**Comment by ajborla** [comment]
Currently re-evaluating choice of unit test framework.

**Comment by axtens** [comment]
Yes, that's a tricky question. In the COBOL track we went through I think
two other possibilities before we settled on the current. As for the 8th
track, I had to write my own.

**Comment by ajborla** [comment]
The BATS approach initially looked suitable, but it requires the Rexx scripts to emit output. Simple, doable, but clunky. I would like something a little more elegant.

So, I can go the custom route, but I think extending t-rexx (to return success / failure code, emit TAP output, and trap STDOUT-bound output from Rexx SAY) more meets the elegance criterion, plus gives that project more exposure as the official unit test framework for Exercism Rexx. Will be proceeding with this after I have implemented a few more Practice Exercise skeletons.

**Comment by ajborla** [comment]
I have marked off exercises I will be implementing over the next few weeks.

**Comment by ajborla** [comment]
Replacement test unit framework appears to be meeting expectations. Two practice exercises down, approximately twenty-odd to go ...

**Comment by ajborla** [comment]
Continuing to implement exercises, and will do so until 20+ exercise target met. Will then start unit test framework overhaul.

**Comment by ajborla** [comment]
Since I am ahead of my self-imposed schedule, and am enjoying implementing  these exercises so much, I am aiming to implement 40+ exercises before proceeding to a subsequent stage (either unit test framework expansion, or CI tasks).

**Comment by ajborla** [comment]
Just hit 51 exercise implementations. Will cease at 71, then move onto subsequent stages.

**Comment by axtens** [comment]
Wow. I stopped at 20 for civil and 8th as that was the bare minimum and I
was impatient.

**Comment by ajborla** [comment]
This will, most likely, be my only Exercism track, so I want to make it as solid, and substantial, a piece of work as I can.

**Comment by axtens** [comment]
Fair call. You can add tasks post-launch.
